apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatappfrontend
  labels:
    app: chatappfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatappfrontend
  template:
    metadata:
      labels:
        app: chatappfrontend
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: chatappfrontend 
        image: gcr.io/umg-social-tech/front:v1
        env:
        - name: REACT_APP_API_URL
          value: https://umgsocial.tech/api
        - name: REACT_APP_SOCKET
          value: https://umgsocial.tech/

        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 500m