apiVersion: v1
kind: Service
metadata:
  name: uwuchatapp-frontend-service
spec:
  selector:
    app: chatappfrontend
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uwuchatapp-frontend-certificate
  namespace: front
spec:
  secretName: uwuchatapp-frontend-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - uwu.umgsocial.tech
