apiVersion: v1
kind: ServiceAccount
metadata:
  name: skooner-sa
  namespace: kube-system #whichever namespace you deployed skooner dashboard to
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skooner-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: skooner-sa
  namespace: kube-system #whichever namespace you deployed skooner dashboard to
---
apiVersion: v1
kind: Secret
metadata:
  name: skooner-sa-token
  namespace: kube-system #whichever namespace you deployed skooner dashboard to
  annotations:
   kubernetes.io/service-account.name: skooner-sa
type: kubernetes.io/service-account-token
---