apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: chat-probe
  labels:
    release: prometheus
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - http://104.197.23.35